### PR TITLE
chore: fix CI

### PR DESCRIPTION
**Pull request by MichaelDeBoey**

### CODE REVIEW

**Comment by MichaelDeBoey** [comment]
@Aslemammad It seems like CI is broken, because we're now testing against all supported `esbuild` versions (as of #14)
But the snapshot appears to be different with each `esbuild` version

Any idea on how to fix this?
This will break each time `esbuild` updates I'm afraid 🤔
So honestly I would just delete the snapshot tests, as I can't come up with a better solution tbh 🤔

**Comment by Aslemammad** [comment]
I see, we cannot do that! Where it fails exactly? disable it there, but with snapshots, it's better to keep them.

**Comment by MichaelDeBoey** [comment]
@Aslemammad The test itself doesn't fail, but the output for `polyfillContent` is different for different `esbuild` versions

These tests are run with `esbuild@0.14.54`, which appears to be different from [`0.14.0`](https://github.com/Aslemammad/modern-node-polyfills/actions/runs/5235132645/jobs/9451747989?pr=16#step:8:329), slightly different from [`0.16.0`](https://github.com/Aslemammad/modern-node-polyfills/actions/runs/5235132645/jobs/9451751530?pr=16#step:8:172), a bit more different from [`0.16.x`](https://github.com/Aslemammad/modern-node-polyfills/actions/runs/5235132645/jobs/9451752781?pr=16#step:8:172) & [`0.17.0`](https://github.com/Aslemammad/modern-node-polyfills/actions/runs/5235132645/jobs/9451753780?pr=16#step:8:172), and even more different from [`0.17.x`](https://github.com/Aslemammad/modern-node-polyfills/actions/runs/5235132645/jobs/9451754645?pr=16#step:8:172), [`0.18.0`](https://github.com/Aslemammad/modern-node-polyfills/actions/runs/5235132645/jobs/9451755461?pr=16#step:8:204) & [`0.18.x`](https://github.com/Aslemammad/modern-node-polyfills/actions/runs/5235132645/jobs/9451756443?pr=16#step:8:204)

**Comment by Aslemammad** [comment]
That's a funny case :) 
How about testing with 'string.includes' instead snapshotting?

**Comment by MichaelDeBoey** [comment]
@Aslemammad I can definitely do that.
What string would you test against?

I could test against `@jspm/core/nodelibs/browser/buffer.js` or so, but that would mean that if they ever decide to change their internal structure, tests will break for no reason again

**Comment by Aslemammad** [comment]
I meant testing against the polyfills in the functions, for instance checking if a global object gets polyfilled or a node module, exactly  like the current tests.

**Comment by MichaelDeBoey** [comment]
@Aslemammad Can you help out on that one please?
The snapshot contains minified code, so it's _really_ hard to see what's actually polyfilled for me

**Comment by Aslemammad** [comment]
@MichaelDeBoey can we test with esbuild 18 only?

**Comment by MichaelDeBoey** [comment]
@Aslemammad Done

**Pull request merged**
