### PR TITLE
chore: update dependencies

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
#16 needs to be merged first

### CODE REVIEW

**Comment by Aslemammad** [comment]
Conflicts & tests failing!

**Comment by Aslemammad** [comment]
And also check the main ci & cd if possible, thanks.

**Comment by MichaelDeBoey** [comment]
@Aslemammad Fixed conflicts
Main CI will be fixed by #16

**Comment by Aslemammad** [comment]
I merged the other one, this one is only remaining, do you know why It  fails?

**Comment by MichaelDeBoey** [comment]
@Aslemammad All tests are passing now

**Comment by Aslemammad** [comment]
Thanks. great job.

**Pull request merged**
