### PR TITLE
fix: polyfilling fs/promises

### LINKED ISSUE #6: Failed to polyfill `fs/promises`
Calling `polyfillPath` with `fs/promises` fails due to this line:

```ts
  const jspmPath = resolve(
    require.resolve(`@jspm/core/nodelibs/${module}`),
    "../../.."
  );
```

I'ld suggest maybe this workaround:

```ts
  const jspmPath = resolve(
    require.resolve(`@jspm/core/nodelibs/${module}`),
    "../../.." + (module.includes('/') ? "/.." : "")
  );
```

Happy to make a PR if we agree on a resolution.

### PR DESCRIPTION
**Pull request by christian-bromann**
Fixes #6

I changed the way `polyfillPath` is tested and removed the snapshots that contain tons of code that might changes during version updates. IMO checking if the path ends in a certain way is all we need to test.

### CODE REVIEW

**Comment by Aslemammad** [comment]
Windows tests failing.

**Comment by christian-bromann** [comment]
Pushed a patch that will hopefully fix the test on Windows.

**Comment by Aslemammad** [comment]
New errors.

**Comment by Aslemammad** [comment]
New errors.

**Pull request merged**
